[env:sc01plus]
platform = espressif32
board = esp32-s3-devkitc1-n16r2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
board_build.f_cpu = 240000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -Wl,--wrap=ble_svc_gap_device_name
build_src_filter = +<*> +<buddies/>
lib_deps =
    lovyan03/LovyanGFX @ ^1.2.0
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
